### ISSUE TITLE
컬러에 대한 정의

### ISSUE THREAD

**Issue by DaYoung-woo** [CheerUpTwogether/Piggy#30]
font color weight size 순으로 정의해두려고 합니다
ex) fontPrimaryBold20, fontPrimaryBold18, fontPrimaryBold20  
  
컬러에 대한 모호함이 있습니다.  
현재 사용하는 컬러들입니다.  
- #ED423F: primary(메인 색상)
- #04BF8A: sub(초록색)
- #efefef
- #AAAAAA
- #999999
- #777777
- #333333  
사용되는 회색-검정 색상들에 대한 정의가 필요할 것 같습니다.

<img width="363" alt="image" src="https://github.com/user-attachments/assets/386f0360-b1c7-4f27-88e4-4f71e16f7332">. 
공통 스타일 정의를 이렇게 하려고 하는데 어떠신가요?

**Comment by DaYoung-woo** [comment]
<img width="402" alt="image" src="https://github.com/user-attachments/assets/11d4b442-3f37-4128-820d-c462918dd349">

text에는 prefix를 사용하지 않고 background일 때만 bg prefix를 쓰는 방식은 어떠신가요?

**Comment by mymain838** [comment]
> font color weight size 순으로 정의해두려고 합니다 ex) fontPrimaryBold20, fontPrimaryBold18, fontPrimaryBold20
> 
> 컬러에 대한 모호함이 있습니다. 현재 사용하는 컬러들입니다.
> 
> * #ED423F: primary(메인 색상)
> * #04BF8A: sub(초록색)
> * #efefef
> * #AAAAAA
> * #999999
> * #777777
> * #333333
>   사용되는 회색-검정 색상들에 대한 정의가 필요할 것 같습니다.
> 
> <img alt="image" width="363" src="https://private-user-images.githubusercontent.com/131967254/358879487-386f0360-b1c7-4f27-88e4-4f71e16f7332.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5NTI1NTAsIm5iZiI6MTcyMzk1MjI1MCwicGF0aCI6Ii8xMzE5NjcyNTQvMzU4ODc5NDg3LTM4NmYwMzYwLWIxYzctNGYyNy04OGU0LTRmNzFlMTZmNzMzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxOFQwMzM3MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmZiNDIxNGJiZGZiMWU0ODVlNjBhNTBlMmM4MDA5YmZlMzU5OTBiOTBlOTA0MWVlNTEwMjg3NzcyMDQwNGYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xHXRVyv66oMCyO8NgVu5Pbsw3RMRjnmG9M1SIAxmZ-o">. 공통 스타일 정의를 이렇게 하려고 하는데 어떠신가요?

좋습니다

**Comment by AmitaWhite** [comment]
네. 어떤 이슈, 어떤 상황에 대한 얘기인지 이따 14시에 코드리뷰 할 때 먼저 설명 부탁드립니다.

**Comment by DaYoung-woo** [comment]
넵 2시에 다시 언급하겠습니당!

**Comment by dhdpekfa1** [comment]
사용하는 fontSize, fontWeight, color를 다 설정하는 건지도 이야기 해보면 좋을 것 같아요!

**Comment by DaYoung-woo** [comment]
넵 좋습니당!
개인적으로 fontSize, fontWeight, color 한번에 다 설정해둔 style과  
fontSize, fontWeight, color 각각 따로따로 설정해둔 style 모두 작성하는 것이 좋을 것 같습니당

**Comment by DaYoung-woo** [comment]
#ED423F: primary(메인 색상)
#04BF8A: sub(초록색)
#EFEFEF: ef
#AAAAAA:  a
#999999: 9
#777777: 7
#333333: 3
